db.url=jdbc:mysql://mysql-container:3306/transito_sp?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowLoadLocalInfile=true
db.usuario=root
db.senha=root123
etl.tamanho.lote=5000
etl.fonte=S3
etl.local.pasta=
etl.s3.bucket=meu-bucket-new-road
etl.s3.prefixo=meuArquivo/
etl.s3.regiao=us-east-1