# Conexão MySQL
db.url=
db.username=
db.password=

# AWS S3
s3.region=us-east-1
s3.bucket=meu-bucket-new-road
s3.key=meuArquivo/entrada.xlsx

# Transformação
transform.prefixo=[ETL]
transform.sufixo=[OK]
