# Conexão MySQL
db.url=jdbc:mysql://localhost:3306/etldb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo
db.username=root
db.password=sua_senha

# AWS S3
s3.region=us-east-1
s3.bucket=
s3.key=

# Transformação
transform.prefixo=[ETL]
transform.sufixo=[OK]